import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/userInfo.authProvide";
import ConditionalLayout from "@/components/common/ConditionalLayout";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, getLocale } from "next-intl/server";
// import { GlobalSmoothScroll } from "@/hooks/scroll-smooth";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-gray-50 `}>
        <AuthProvider>
          <NextIntlClientProvider messages={messages} locale={locale}>
            <ConditionalLayout>
              {/* <GlobalSmoothScroll /> */}
              {children}
            </ConditionalLayout>
          </NextIntlClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
